# Cloudflare Pages Configuration
name = "biocatch-onboarding"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

# This configuration applies to Cloudflare Pages deployments
pages_build_output_dir = ".vercel/output/static"

