import type { Poc, PocFile, SignalIdea } from "@/lib/types";
import { generateId } from "@/lib/db/store";

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .slice(0, 40);
}

function generateJsSignal(idea: SignalIdea): PocFile[] {
  const slug = slugify(idea.title);

  const signalFile = `/**
 * PoC Signal: ${idea.title}
 * Generated by SignalForge PoC Agent
 * Collection Layer: ${idea.collectionLayer}
 * Platforms: ${idea.platforms.join(", ")}
 */

export interface ${toPascalCase(slug)}Result {
  score: number;
  indicators: Record<string, number | boolean>;
  timestamp: number;
}

const MUTATION_BURST_THRESHOLD_MS = 50;
const MIN_MUTATIONS_FOR_BURST = 3;

let mutationTimestamps: number[] = [];
let focusTransitions: string[] = [];

export function init${toPascalCase(slug)}Collector(): void {
  if (typeof document === "undefined") return;

  const observer = new MutationObserver((mutations) => {
    if (mutations.length > 0) {
      mutationTimestamps.push(performance.now());
      if (mutationTimestamps.length > 100) {
        mutationTimestamps = mutationTimestamps.slice(-100);
      }
    }
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
  });

  document.addEventListener("focusin", (e) => {
    const target = (e.target as HTMLElement)?.tagName ?? "unknown";
    focusTransitions.push(target);
    if (focusTransitions.length > 50) {
      focusTransitions = focusTransitions.slice(-50);
    }
  });
}

function detectMutationBursts(timestamps: number[]): number {
  if (timestamps.length < MIN_MUTATIONS_FOR_BURST) return 0;

  let burstCount = 0;
  for (let i = 2; i < timestamps.length; i++) {
    const gap1 = timestamps[i - 1] - timestamps[i - 2];
    const gap2 = timestamps[i] - timestamps[i - 1];
    if (gap1 < MUTATION_BURST_THRESHOLD_MS && gap2 < MUTATION_BURST_THRESHOLD_MS) {
      burstCount++;
    }
  }
  return burstCount;
}

function computeFocusRegularity(transitions: string[]): number {
  if (transitions.length < 4) return 0;

  const unique = new Set(transitions);
  const repetitionRate = 1 - unique.size / transitions.length;
  return Math.min(1, repetitionRate * 2);
}

export function collect${toPascalCase(slug)}(): ${toPascalCase(slug)}Result {
  const burstCount = detectMutationBursts(mutationTimestamps);
  const focusRegularity = computeFocusRegularity(focusTransitions);
  const agenticScore = Math.min(1, burstCount * 0.15 + focusRegularity * 0.5);

  return {
    score: agenticScore,
    indicators: {
      mutationBurstCount: burstCount,
      focusRegularity,
      isAgenticLikely: agenticScore > 0.6,
    },
    timestamp: Date.now(),
  };
}

export function reset${toPascalCase(slug)}State(): void {
  mutationTimestamps = [];
  focusTransitions = [];
}
`;

  const testFile = `import {
  init${toPascalCase(slug)}Collector,
  collect${toPascalCase(slug)},
  reset${toPascalCase(slug)}State,
} from "./${slug}Signal";

describe("${idea.title}", () => {
  beforeEach(() => {
    reset${toPascalCase(slug)}State();
  });

  it("returns low score with no activity", () => {
    const result = collect${toPascalCase(slug)}();
    expect(result.score).toBeLessThan(0.3);
    expect(result.indicators.isAgenticLikely).toBe(false);
  });

  it("detects mutation burst patterns", () => {
    // Simulated burst injection for PoC validation
    const mockTimestamps = [0, 10, 20, 30, 100, 500];
    // In real validation, Playwright sessions inject actual DOM mutations
    expect(mockTimestamps.length).toBeGreaterThan(2);
  });

  it("includes required data fields", () => {
    const result = collect${toPascalCase(slug)}();
    expect(result).toHaveProperty("score");
    expect(result).toHaveProperty("indicators");
    expect(result).toHaveProperty("timestamp");
  });
});
`;

  return [
    { path: `signals/${slug}Signal.ts`, content: signalFile },
    { path: `tests/${slug}Signal.test.ts`, content: testFile },
    {
      path: "README.md",
      content: `# PoC: ${idea.title}

## Signal Type
${idea.signalType}

## Required Data
${idea.requiredData.map((d) => `- ${d}`).join("\n")}

## Usage
\`\`\`typescript
import { init${toPascalCase(slug)}Collector, collect${toPascalCase(slug)} } from './signals/${slug}Signal';

init${toPascalCase(slug)}Collector();
const result = collect${toPascalCase(slug)}();
console.log(result);
\`\`\`

## Validation
Run Playwright vs normal browser sessions and compare \`score\` distribution.
`,
    },
  ];
}

function toPascalCase(str: string): string {
  return str
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

export function generatePoc(idea: SignalIdea): Poc {
  const now = new Date().toISOString();
  const files = generateJsSignal(idea);

  return {
    id: generateId("poc"),
    ideaId: idea.id,
    type: "javascript",
    files,
    instructions: "Review generated signal code, run validation lab to compare Playwright vs browser sessions.",
    status: "ready",
    createdAt: now,
  };
}
