import type { CatalogSignal, IdeaScores, SignalCategory } from "@/lib/types";

const DEFAULT_SCORES: IdeaScores = {
  detectionValue: 0.7,
  novelty: 0.55,
  customerRelevance: 0.65,
  arrImpact: 0.6,
  engineeringCost: 0.4,
  latencyCost: 0.2,
  privacyRisk: 0.15,
  falsePositiveRisk: 0.3,
  crossPlatformPotential: 0.6,
  competitiveAdvantage: 0.55,
};

function scores(partial: Partial<IdeaScores>): IdeaScores {
  return { ...DEFAULT_SCORES, ...partial };
}

export const CATEGORY_META: Record<
  SignalCategory,
  { label: string; description: string }
> = {
  behavioral_biometrics: {
    label: "Behavioral Biometrics",
    description:
      "How the user physically interacts — mouse, touch, keystrokes, motion, and navigation rhythm.",
  },
  agentic_ai: {
    label: "Agentic & AI",
    description:
      "AI agents and LLM-driven browsers that plan and execute flows without a human in the loop.",
  },
  automation_bot: {
    label: "Automation & Bots",
    description:
      "Headless browsers, automation frameworks, RPA tooling, and scripted attack traffic.",
  },
  device_hardware: {
    label: "Device & Hardware",
    description:
      "Stable device identity from rendering, audio, sensors, fonts, and hardware capabilities.",
  },
  network_edge: {
    label: "Network & Edge",
    description:
      "Transport-layer and infrastructure signals available at the CDN, edge, and backend.",
  },
  environmental: {
    label: "Environment",
    description:
      "Emulators, virtual machines, screen sharing, and locale/timezone inconsistencies.",
  },
  fraud_pattern: {
    label: "Fraud Patterns",
    description:
      "Higher-order detections: RATs, social-engineering scams, account takeover, and mule activity.",
  },
};

export const CATEGORY_ORDER: SignalCategory[] = [
  "behavioral_biometrics",
  "agentic_ai",
  "automation_bot",
  "device_hardware",
  "network_edge",
  "environmental",
  "fraud_pattern",
];

export const SIGNAL_CATALOG: CatalogSignal[] = [
  // ── Behavioral Biometrics ──────────────────────────────────────────────
  {
    id: "sig_mouse_dynamics",
    name: "Mouse movement dynamics",
    category: "behavioral_biometrics",
    description:
      "Model cursor velocity, acceleration, jerk, and path curvature. Humans produce noisy ballistic movements; scripts and agents produce straight, uniform, or teleported paths.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["pointermove events", "timestamps", "cursor coordinates"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["mouse", "pointer", "cursor", "biometric"],
    scores: scores({ detectionValue: 0.85, customerRelevance: 0.85, crossPlatformPotential: 0.5 }),
  },
  {
    id: "sig_keystroke_dynamics",
    name: "Keystroke dynamics",
    category: "behavioral_biometrics",
    description:
      "Measure dwell time (key down→up) and flight time (key→key) to build a typing rhythm profile. Distinguishes humans from paste, injection, and synthetic key events.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web", "ios", "android"],
    collectionLayer: "JS SDK",
    requiredData: ["keydown/keyup timing", "inter-key intervals", "key codes"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "medium",
    matchKeywords: ["keystroke", "typing", "keyboard", "biometric"],
    scores: scores({ detectionValue: 0.86, novelty: 0.5, crossPlatformPotential: 0.85 }),
  },
  {
    id: "sig_touch_dynamics",
    name: "Touch & swipe dynamics",
    category: "behavioral_biometrics",
    description:
      "Capture touch pressure, contact area, swipe velocity, and multi-touch geometry on mobile. Emulated touches lack pressure variance and natural curvature.",
    signalType: "behavioral",
    platforms: ["mobile_web", "ios", "android"],
    collectionLayer: "JS SDK",
    requiredData: ["touch pressure", "contact radius", "swipe velocity", "gesture geometry"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["touch", "swipe", "gesture", "mobile", "biometric"],
    scores: scores({ detectionValue: 0.84, customerRelevance: 0.8, crossPlatformPotential: 0.7 }),
  },
  {
    id: "sig_device_motion",
    name: "Device motion & orientation",
    category: "behavioral_biometrics",
    description:
      "Use accelerometer and gyroscope streams to detect natural hand tremor and holding posture. Emulators and bots report static, absent, or perfectly periodic motion.",
    signalType: "behavioral",
    platforms: ["mobile_web", "ios", "android"],
    collectionLayer: "JS SDK",
    requiredData: ["accelerometer", "gyroscope", "device orientation"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["accelerometer", "gyroscope", "motion", "orientation", "sensor"],
    scores: scores({ detectionValue: 0.82, novelty: 0.65, falsePositiveRisk: 0.2 }),
  },
  {
    id: "sig_scroll_dynamics",
    name: "Scroll behavior dynamics",
    category: "behavioral_biometrics",
    description:
      "Analyze scroll acceleration, momentum decay, and correction patterns. Programmatic scrolling is uniform and lacks the overshoot-and-correct signature of humans.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["scroll deltas", "scroll timing", "momentum decay"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["scroll", "wheel", "momentum"],
    scores: scores({ detectionValue: 0.72, novelty: 0.5 }),
  },
  {
    id: "sig_navigation_flow",
    name: "Navigation & field-flow patterns",
    category: "behavioral_biometrics",
    description:
      "Track field focus order, tab usage, and page traversal sequences. Automated flows follow DOM order perfectly and skip the exploratory backtracking humans exhibit.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["focus events", "field order", "navigation timing"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["navigation", "field", "focus", "form flow"],
    scores: scores({ detectionValue: 0.74, customerRelevance: 0.75 }),
  },
  {
    id: "sig_data_familiarity",
    name: "Data familiarity",
    category: "behavioral_biometrics",
    description:
      "Measure how fluently a user enters their own data. Genuine owners type PII from memory in bursts; fraudsters read, hesitate, and correct — a strong new-account and ATO signal.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web", "ios", "android"],
    collectionLayer: "JS SDK",
    requiredData: ["field entry timing", "hesitation gaps", "correction counts"],
    expectedValue: "critical",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "medium",
    matchKeywords: ["familiarity", "fluency", "hesitation", "onboarding"],
    scores: scores({ detectionValue: 0.9, customerRelevance: 0.92, arrImpact: 0.85, novelty: 0.75 }),
  },
  {
    id: "sig_segmented_typing",
    name: "Hesitation & segmented typing",
    category: "behavioral_biometrics",
    description:
      "Detect copy-segment-paste and read-and-type patterns where data is entered in unnatural chunks with long pauses — common when a victim is coached or data is read from a note.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["inter-keystroke gaps", "burst segmentation", "pause distribution"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["hesitation", "segmented", "pause", "coaching"],
    scores: scores({ detectionValue: 0.8, customerRelevance: 0.8 }),
  },
  {
    id: "sig_paste_autofill",
    name: "Copy/paste & autofill behavior",
    category: "behavioral_biometrics",
    description:
      "Flag paste and browser-autofill into sensitive fields. High paste rates on credentials and beneficiary fields correlate with credential stuffing and mule onboarding.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["paste events", "autofill events", "input mutation source"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["paste", "autofill", "clipboard"],
    scores: scores({ detectionValue: 0.7, novelty: 0.4 }),
  },
  {
    id: "sig_biometric_drift",
    name: "Behavioral profile drift",
    category: "behavioral_biometrics",
    description:
      "Compare live behavioral biometrics against the account's enrolled profile. Sudden divergence in typing, mouse, or motion signatures flags account takeover mid-session.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web", "ios", "android"],
    collectionLayer: "Backend",
    requiredData: ["enrolled biometric profile", "live session vectors", "similarity score"],
    expectedValue: "critical",
    falsePositiveRisk: "high",
    engineeringDifficulty: "high",
    privacyRisk: "medium",
    matchKeywords: ["drift", "continuous authentication", "profile", "takeover"],
    scores: scores({ detectionValue: 0.92, arrImpact: 0.88, engineeringCost: 0.7, falsePositiveRisk: 0.5 }),
  },

  // ── Agentic & AI ───────────────────────────────────────────────────────
  {
    id: "sig_dom_planning",
    name: "Agentic DOM planning behavior",
    category: "agentic_ai",
    description:
      "Agentic browsers pre-plan DOM mutations, producing distinctive mutation-burst timing and focus-transition ordering versus reactive human interaction.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["DOM mutations", "mutation burst intervals", "focus transition order"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["dom planning", "agentic", "dom mutation"],
    scores: scores({ detectionValue: 0.9, novelty: 0.85, competitiveAdvantage: 0.8, arrImpact: 0.85 }),
  },
  {
    id: "sig_interaction_entropy",
    name: "Interaction entropy scoring",
    category: "agentic_ai",
    description:
      "Compute session interaction entropy from pointer paths, scroll, and keystroke timing. LLM-driven agents exhibit markedly lower entropy than organic users.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["pointer events", "scroll data", "keystroke timing"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["entropy", "llm", "agentic", "ai agent"],
    scores: scores({ detectionValue: 0.88, novelty: 0.9, competitiveAdvantage: 0.85 }),
  },
  {
    id: "sig_agentic_formfill",
    name: "Agentic form-filling detection",
    category: "agentic_ai",
    description:
      "Detect AI-driven form filling on mobile web that mimics human timing. Combines touch regularity, viewport interaction, and field-focus sequencing.",
    signalType: "behavioral",
    platforms: ["mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["touch events", "form interactions", "viewport data", "focus sequences"],
    expectedValue: "critical",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["form filling", "agentic", "mobile web", "ai-driven"],
    scores: scores({ detectionValue: 0.92, customerRelevance: 0.95, arrImpact: 0.9, engineeringCost: 0.6 }),
  },
  {
    id: "sig_agentic_navigation",
    name: "Goal-directed agentic navigation",
    category: "agentic_ai",
    description:
      "Identify perfectly goal-directed traversal with no exploratory hovering, dead-clicks, or reading pauses — a hallmark of task-executing AI agents.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["click targets", "dwell time per element", "exploration ratio"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["agentic", "navigation", "goal-directed", "ai agent"],
    scores: scores({ detectionValue: 0.83, novelty: 0.8 }),
  },
  {
    id: "sig_synthetic_pointer",
    name: "Synthetic pointer path detection",
    category: "agentic_ai",
    description:
      "Detect programmatically generated pointer paths (Bezier smoothing, dispatched events) used by agents to spoof human mouse movement.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["pointer event isTrusted", "path smoothness", "dispatch signatures"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["synthetic pointer", "istrusted", "dispatched", "bezier"],
    scores: scores({ detectionValue: 0.82, falsePositiveRisk: 0.15 }),
  },

  // ── Automation & Bots ──────────────────────────────────────────────────
  {
    id: "sig_webdriver_flag",
    name: "WebDriver flag & bindings",
    category: "automation_bot",
    description:
      "Probe navigator.webdriver plus injected automation bindings and DOM artifacts left by Selenium and WebDriver-based tools.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["navigator.webdriver", "automation globals", "DOM artifacts"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["webdriver", "selenium", "automation"],
    scores: scores({ detectionValue: 0.7, novelty: 0.3, falsePositiveRisk: 0.1 }),
  },
  {
    id: "sig_cdp_session",
    name: "CDP session fingerprint",
    category: "automation_bot",
    description:
      "Detect active Chrome DevTools Protocol sessions and framework-specific API signatures via timing side-channels and capability probes.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["CDP indicators", "API availability", "timing side-channels"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["cdp", "devtools protocol", "playwright", "puppeteer"],
    scores: scores({ detectionValue: 0.82, falsePositiveRisk: 0.15 }),
  },
  {
    id: "sig_headless_indicators",
    name: "Headless browser indicators",
    category: "automation_bot",
    description:
      "Aggregate headless tells: missing plugins, permission anomalies, renderer strings, and absent chrome runtime — resilient to individual patches.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["plugin list", "permissions", "renderer strings", "chrome runtime"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["headless", "chrome", "phantom"],
    scores: scores({ detectionValue: 0.78, novelty: 0.4 }),
  },
  {
    id: "sig_framework_signature",
    name: "Automation framework signature",
    category: "automation_bot",
    description:
      "Fingerprint Playwright, Puppeteer, and Selenium by their unique injected globals, event dispatch patterns, and default viewport/UA combinations.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["injected globals", "event dispatch patterns", "default configs"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["playwright", "puppeteer", "selenium", "framework"],
    scores: scores({ detectionValue: 0.8, falsePositiveRisk: 0.15 }),
  },
  {
    id: "sig_stealth_inconsistency",
    name: "Stealth-plugin inconsistency",
    category: "automation_bot",
    description:
      "Catch stealth toolkits by cross-checking properties they spoof: WebGL vendor vs UA, navigator overrides, and permission/plugin mismatches.",
    signalType: "environmental",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["webgl vendor", "navigator consistency", "spoof signatures"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["stealth", "evasion", "spoof", "inconsistency"],
    scores: scores({ detectionValue: 0.81, novelty: 0.7 }),
  },
  {
    id: "sig_rpa_detection",
    name: "RPA tool detection",
    category: "automation_bot",
    description:
      "Detect desktop RPA (UiPath, Automation Anywhere, Power Automate) driving a real browser through native OS-level input with machine-precise timing.",
    signalType: "automation",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["input timing precision", "window focus patterns", "OS-level event cadence"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["rpa", "uipath", "automation anywhere", "robotic"],
    scores: scores({ detectionValue: 0.72, novelty: 0.75, engineeringCost: 0.65 }),
  },

  // ── Device & Hardware ──────────────────────────────────────────────────
  {
    id: "sig_canvas_fp",
    name: "Canvas fingerprint",
    category: "device_hardware",
    description:
      "Render text and shapes to a canvas and hash pixel output. Stable per GPU/driver/OS; spoofing adds detectable noise or perfect uniformity.",
    signalType: "device",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["canvas pixel hash", "render timing"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "medium",
    matchKeywords: ["canvas", "fingerprint"],
    scores: scores({ detectionValue: 0.68, novelty: 0.3, privacyRisk: 0.35 }),
  },
  {
    id: "sig_webgl_fp",
    name: "WebGL vendor/renderer fingerprint",
    category: "device_hardware",
    description:
      "Read the unmasked GPU vendor and renderer plus WebGL parameter set. Datacenter GPUs (SwiftShader, llvmpipe) reveal virtualized automation environments.",
    signalType: "device",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["webgl vendor", "webgl renderer", "webgl params"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "medium",
    matchKeywords: ["webgl", "gpu", "renderer", "swiftshader"],
    scores: scores({ detectionValue: 0.76 }),
  },
  {
    id: "sig_audio_fp",
    name: "Audio context fingerprint",
    category: "device_hardware",
    description:
      "Derive a fingerprint from the AudioContext oscillator/compressor output. Consistent per device stack and hard to spoof without artifacts.",
    signalType: "device",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["audio context output hash"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "medium",
    matchKeywords: ["audio", "fingerprint", "oscillator"],
    scores: scores({ detectionValue: 0.66, novelty: 0.45 }),
  },
  {
    id: "sig_font_enum",
    name: "Font enumeration fingerprint",
    category: "device_hardware",
    description:
      "Enumerate installed fonts via measurement. Missing standard fonts or an implausible set exposes headless and containerized environments.",
    signalType: "device",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["font metrics", "available font list"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "medium",
    matchKeywords: ["font", "enumeration", "fingerprint"],
    scores: scores({ detectionValue: 0.62, novelty: 0.35 }),
  },
  {
    id: "sig_screen_viewport",
    name: "Screen & viewport fingerprint",
    category: "device_hardware",
    description:
      "Combine screen resolution, color depth, pixel ratio, and viewport. Impossible geometries and default automation viewports are strong bot tells.",
    signalType: "device",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["screen dimensions", "devicePixelRatio", "viewport size"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["screen", "viewport", "resolution"],
    scores: scores({ detectionValue: 0.6, novelty: 0.3 }),
  },
  {
    id: "sig_hardware_caps",
    name: "Hardware concurrency & memory",
    category: "device_hardware",
    description:
      "Cross-check navigator.hardwareConcurrency and deviceMemory against the claimed device class. Datacenter VMs report anomalous CPU/RAM profiles.",
    signalType: "device",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["hardwareConcurrency", "deviceMemory", "performance timing"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["hardware", "concurrency", "memory", "cpu"],
    scores: scores({ detectionValue: 0.6, novelty: 0.35 }),
  },
  {
    id: "sig_sensor_fp",
    name: "Mobile sensor fingerprint",
    category: "device_hardware",
    description:
      "Fingerprint accelerometer/gyroscope calibration bias unique to each physical device. Emulators lack real sensor noise entirely.",
    signalType: "device",
    platforms: ["ios", "android", "mobile_web"],
    collectionLayer: "iOS SDK",
    requiredData: ["sensor calibration bias", "noise floor", "sampling jitter"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["sensor", "accelerometer", "calibration", "mobile"],
    scores: scores({ detectionValue: 0.8, novelty: 0.7 }),
  },
  {
    id: "sig_battery_behavior",
    name: "Battery & power behavior",
    category: "device_hardware",
    description:
      "Observe battery level/charging transitions over the session. Perfectly static 100% charging is common in emulators and cloud phones.",
    signalType: "device",
    platforms: ["mobile_web", "android"],
    collectionLayer: "Android SDK",
    requiredData: ["battery level", "charging state", "level transitions"],
    expectedValue: "low",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["battery", "power", "charging"],
    scores: scores({ detectionValue: 0.5, novelty: 0.5 }),
  },

  // ── Network & Edge ─────────────────────────────────────────────────────
  {
    id: "sig_tls_ja3",
    name: "TLS / JA3 fingerprint",
    category: "network_edge",
    description:
      "Fingerprint the TLS ClientHello (JA3/JA4) at the edge. Automation stacks and custom HTTP clients produce fingerprints that mismatch the claimed browser.",
    signalType: "network",
    platforms: ["edge", "backend"],
    collectionLayer: "CDN/Edge",
    requiredData: ["TLS ClientHello", "cipher suites", "extensions order"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["tls", "ja3", "ja4", "clienthello", "edge"],
    scores: scores({ detectionValue: 0.85, novelty: 0.6, engineeringCost: 0.65, crossPlatformPotential: 0.7 }),
  },
  {
    id: "sig_ip_intel",
    name: "IP reputation & proxy detection",
    category: "network_edge",
    description:
      "Classify source IPs as datacenter, residential-proxy, VPN, or Tor and score reputation. Residential proxy networks are heavily used for fraud at scale.",
    signalType: "network",
    platforms: ["edge", "backend"],
    collectionLayer: "CDN/Edge",
    requiredData: ["source IP", "ASN", "proxy/VPN classification", "reputation feeds"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["ip", "proxy", "vpn", "datacenter", "reputation"],
    scores: scores({ detectionValue: 0.8, customerRelevance: 0.85, novelty: 0.3 }),
  },
  {
    id: "sig_header_anomaly",
    name: "HTTP header order & anomaly",
    category: "network_edge",
    description:
      "Compare HTTP header ordering, casing, and presence against known browser profiles. Non-browser clients and mismatched UAs reorder or omit headers.",
    signalType: "network",
    platforms: ["edge", "backend"],
    collectionLayer: "CDN/Edge",
    requiredData: ["header order", "header casing", "accept headers"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["header", "anomaly", "ordering", "edge"],
    scores: scores({ detectionValue: 0.72, novelty: 0.5 }),
  },
  {
    id: "sig_http2_fp",
    name: "HTTP/2 & QUIC fingerprint",
    category: "network_edge",
    description:
      "Fingerprint HTTP/2 SETTINGS frames, stream priorities, and QUIC parameters. Reveals the true client stack independent of spoofed user-agent.",
    signalType: "network",
    platforms: ["edge", "backend"],
    collectionLayer: "CDN/Edge",
    requiredData: ["http2 settings frame", "stream priorities", "quic params"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["http2", "quic", "settings frame", "akamai"],
    scores: scores({ detectionValue: 0.82, novelty: 0.7, engineeringCost: 0.7 }),
  },
  {
    id: "sig_edge_rate",
    name: "Edge request timing & velocity",
    category: "network_edge",
    description:
      "Score request cadence, inter-arrival regularity, and endpoint sequencing at the edge to catch scripted, distributed, and burst traffic before it reaches origin.",
    signalType: "network",
    platforms: ["edge", "backend"],
    collectionLayer: "CDN/Edge",
    requiredData: ["request timestamps", "endpoint sequence", "session velocity"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["rate", "velocity", "cadence", "edge", "cloudflare"],
    scores: scores({ detectionValue: 0.7 }),
  },

  // ── Environment ────────────────────────────────────────────────────────
  {
    id: "sig_locale_mismatch",
    name: "Timezone / locale mismatch",
    category: "environmental",
    description:
      "Cross-check JS timezone, language, and Intl locale against IP geolocation and Accept-Language. Mismatches expose proxied and misconfigured automation.",
    signalType: "environmental",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["Intl timezone", "navigator.language", "IP geo", "Accept-Language"],
    expectedValue: "medium",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "low",
    privacyRisk: "low",
    matchKeywords: ["timezone", "locale", "language", "geo"],
    scores: scores({ detectionValue: 0.68, novelty: 0.35 }),
  },
  {
    id: "sig_emulator_vm",
    name: "Emulator & VM detection",
    category: "environmental",
    description:
      "Detect Android emulators, iOS simulators, and desktop VMs via build props, sensor absence, GPU renderers, and timing artifacts.",
    signalType: "environmental",
    platforms: ["android", "ios", "web"],
    collectionLayer: "Android SDK",
    requiredData: ["build props", "sensor presence", "gpu renderer", "timing artifacts"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["emulator", "vm", "virtual machine", "simulator"],
    scores: scores({ detectionValue: 0.82, customerRelevance: 0.8 }),
  },
  {
    id: "sig_screen_share",
    name: "Screen-sharing & remote control",
    category: "environmental",
    description:
      "Infer active screen sharing or remote control from frame-rate throttling, virtual display adapters, and input-latency signatures — key for scam-in-progress detection.",
    signalType: "environmental",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["frame rate", "display adapter", "input latency"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["screen share", "screen sharing", "remote control", "scam"],
    scores: scores({ detectionValue: 0.85, customerRelevance: 0.9, arrImpact: 0.85, engineeringCost: 0.65 }),
  },
  {
    id: "sig_client_hints",
    name: "Client Hints consistency",
    category: "environmental",
    description:
      "Compare low-entropy Client Hints from the standard API against high-entropy hints and UA. Inconsistency signals spoofing or CDP override.",
    signalType: "environmental",
    platforms: ["web"],
    collectionLayer: "JS SDK",
    requiredData: ["navigator.userAgentData", "high-entropy hints", "UA string"],
    expectedValue: "medium",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["client hints", "useragentdata", "entropy"],
    scores: scores({ detectionValue: 0.72, novelty: 0.6 }),
  },

  // ── Fraud Patterns ─────────────────────────────────────────────────────
  {
    id: "sig_rat_detection",
    name: "Remote Access Tool (RAT) detection",
    category: "fraud_pattern",
    description:
      "Detect TeamViewer/AnyDesk-style remote control during a session via input-latency signatures, event injection patterns, and cursor teleportation.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["input latency", "event injection markers", "cursor jumps"],
    expectedValue: "critical",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["rat", "remote access", "teamviewer", "anydesk", "remote control"],
    scores: scores({ detectionValue: 0.93, customerRelevance: 0.95, arrImpact: 0.9, engineeringCost: 0.65 }),
  },
  {
    id: "sig_social_engineering",
    name: "Social-engineering / scam coaching",
    category: "fraud_pattern",
    description:
      "Detect a victim being coached in real time: long hesitation, phone-call cadence gaps, dictated data entry, and hesitation on beneficiary/amount fields.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web", "ios", "android"],
    collectionLayer: "JS SDK",
    requiredData: ["session duration anomalies", "hesitation on payment fields", "dictation patterns"],
    expectedValue: "critical",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "low",
    matchKeywords: ["social engineering", "scam", "coaching", "victim", "authorized push payment"],
    scores: scores({ detectionValue: 0.92, customerRelevance: 0.95, arrImpact: 0.92, novelty: 0.75, engineeringCost: 0.65 }),
  },
  {
    id: "sig_ato_drift",
    name: "Account takeover behavioral drift",
    category: "fraud_pattern",
    description:
      "Combine behavioral profile drift, new device, and impossible travel into an ATO score triggered on sensitive actions like adding a payee.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web", "ios", "android"],
    collectionLayer: "Backend",
    requiredData: ["behavioral drift score", "device change", "geo velocity", "action risk"],
    expectedValue: "critical",
    falsePositiveRisk: "high",
    engineeringDifficulty: "high",
    privacyRisk: "medium",
    matchKeywords: ["account takeover", "ato", "impossible travel", "payee"],
    scores: scores({ detectionValue: 0.9, customerRelevance: 0.95, arrImpact: 0.9, falsePositiveRisk: 0.5, engineeringCost: 0.7 }),
  },
  {
    id: "sig_new_account_fraud",
    name: "New-account / application fraud",
    category: "fraud_pattern",
    description:
      "Score onboarding sessions using data familiarity, copy/paste rates, and device risk to catch synthetic identities and application fraud at signup.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "JS SDK",
    requiredData: ["data familiarity", "paste rate", "device risk", "form velocity"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "medium",
    privacyRisk: "medium",
    matchKeywords: ["new account", "application fraud", "synthetic identity", "onboarding"],
    scores: scores({ detectionValue: 0.85, customerRelevance: 0.9, arrImpact: 0.85 }),
  },
  {
    id: "sig_mule_account",
    name: "Money mule account patterns",
    category: "fraud_pattern",
    description:
      "Flag mule accounts through behavioral familiarity gaps, unusual beneficiary management, and device/session sharing across otherwise unrelated accounts.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "Backend",
    requiredData: ["beneficiary patterns", "device sharing graph", "familiarity gaps"],
    expectedValue: "high",
    falsePositiveRisk: "medium",
    engineeringDifficulty: "high",
    privacyRisk: "medium",
    matchKeywords: ["mule", "beneficiary", "money laundering", "device sharing"],
    scores: scores({ detectionValue: 0.83, customerRelevance: 0.88, arrImpact: 0.85, engineeringCost: 0.65 }),
  },
  {
    id: "sig_credential_stuffing",
    name: "Credential stuffing & bot login",
    category: "fraud_pattern",
    description:
      "Correlate automation signals, IP intelligence, paste-heavy input, and login velocity to detect distributed credential-stuffing campaigns.",
    signalType: "behavioral",
    platforms: ["web", "mobile_web"],
    collectionLayer: "Backend",
    requiredData: ["automation flags", "ip intelligence", "login velocity", "paste rate"],
    expectedValue: "high",
    falsePositiveRisk: "low",
    engineeringDifficulty: "medium",
    privacyRisk: "low",
    matchKeywords: ["credential stuffing", "bot login", "account checking", "brute force"],
    scores: scores({ detectionValue: 0.84, customerRelevance: 0.85 }),
  },
];

export function getCatalogSignal(id: string): CatalogSignal | undefined {
  return SIGNAL_CATALOG.find((s) => s.id === id);
}

export function groupCatalogByCategory(): Record<SignalCategory, CatalogSignal[]> {
  const grouped = {} as Record<SignalCategory, CatalogSignal[]>;
  for (const category of CATEGORY_ORDER) {
    grouped[category] = SIGNAL_CATALOG.filter((s) => s.category === category);
  }
  return grouped;
}
