# BioCatch Edge Proxy Worker Configuration
# Deploy: wrangler deploy

name = "point-to-bio"
main = "worker.ts"
compatibility_date = "2024-11-01"

[vars]
BIOCATCH_ENDPOINT = "http://localhost:3000/"
CUSTOMER_ID = "dtrackers"
BRAND = "ben"
SYNC_KEYWORDS = ['transaction', 'payment']
ASYNC_KEYWORDS = ['auth', 'login','register','logout']
WAIT_KEYWORDS = ['transaction','payment']